spring:
    profiles:
        active: dev
    datasource:
            url: jdbc:h2:mem:myDb;DB_CLOSE_DELAY=-1
            username:
            password:
    mvc:
        view:
            suffix: .jsp
            prefix: /
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        database: H2
        openInView: false
        show_sql: true
        generate-ddl: true
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true